import {readFileSync} from 'node:fs';
const config=JSON.parse(readFileSync(new URL('../data/ai-toolkit.json',import.meta.url),'utf8'));
const tiers=[
 {name:'Starter',total:29,net:'24.17',count:11,url:'https://edwardluf.gumroad.com/l/uk-ai-compliance-starter',image:'/assets/ai-toolkit-starter.png',fit:'Core policies and working records for everyday AI use.',extra:'AI use policy, governance, tool inventory, complaints procedure, privacy notice insert, incident log, training record, 30-day plan, risk register and owner summary.'},
 {name:'Complete',total:59,net:'49.17',count:19,url:'https://edwardluf.gumroad.com/l/uk-ai-compliance-complete',image:'/assets/ai-toolkit-complete.png',fit:'Every Starter item, plus assessments, safeguards and supplier checks.',extra:'Adds automated-decision assessment, DPIA, lawful-basis and LIA records, vendor due diligence, processor and transfer checks, human review, fairness testing and data subject rights.'}
];
export function aiToolkitOffers(){const bundle=tiers.find(t=>t.name===config.bundleTier);return `<section class="wrap ai-offers" id="ai-toolkit" aria-labelledby="ai-toolkit-heading">
<div class="section-heading"><div><p class="eyebrow">UK AI COMPLIANCE / EDITABLE TOOLKIT</p><h2 id="ai-toolkit-heading">Turn the guidance<br><em>into working records.</em></h2></div><p>Choose the toolkit on its own, or pair it with the UK blueprint below. One-off digital downloads, with editable Word documents, PDF reference copies and Excel workbooks.</p></div>
<div class="ai-tier-grid">${tiers.map(t=>`<article class="ai-tier"><img class="ai-tier-cover" src="${t.image}" alt="UK AI Compliance Toolkit ${t.name} cover" width="1536" height="1536"><div class="ai-tier-copy"><p class="eyebrow">TOOLKIT ONLY / ${t.name.toUpperCase()}</p><h3>${t.name} toolkit</h3><p>${t.fit}</p><p class="ai-delivery"><strong>${t.count} toolkit items</strong><br>${t.count} editable Word files + ${t.count} PDF copies + 2 Excel workbooks</p><p>${t.extra}</p><div class="ai-buy"><strong>£${t.total}</strong><span>UK total including 20% VAT</span></div><a class="button primary" href="${t.url}">Buy ${t.name} toolkit ↗</a><p class="purchase-note">Gumroad displays £${t.net} before VAT. UK checkout total: £${t.total}. Local taxes and tax status may change your total. The blueprint is sold separately.</p></div></article>`).join('')}</div>
<div class="ai-guidance"><h3>Examples, explanations and references included</h3><ul><li>Prepopulated fictional examples in selected working records show how to complete entries and adapt them for your business.</li><li>The risk register includes 14 illustrative risks, worked scoring, likelihood and impact guidance, scores before and after controls, and a heat map.</li><li>A plain-English overview maps 12 requirements to toolkit items. Working documents include legal-basis tables, legislative references, definitions and completion prompts.</li><li>LAW, GUIDANCE, BEST PRACTICE and WATCH labels help distinguish requirements, guidance, recommendations and developments to monitor.</li></ul><p>Starter’s overview also points to tools supplied only in Complete. Replace examples, placeholders and scores with your own details. Even everyday use of personal data may require additional assessments and supplier, lawful-basis or rights checks.</p><details><summary>Software, licence and scope</summary><p>Microsoft Word or a compatible DOCX editor, Microsoft Excel and a PDF reader. PDFs are reference copies, not fillable forms. A computer is recommended; no Notion or Canva account is required.</p><p>v1.2, stated information date 3 October 2026. Single purchasing business, internal use only; no resale or redistribution. Consultants need a separate licence per client. General information and adaptable templates, not legal advice, certification or a compliance guarantee. UK scope; EU AI Act compliance is not included. No subscription or promise of ongoing updates. The separate companion guide and internal manuscript are not included.</p></details></div>
<article class="ai-bundle" id="ai-bundle"><div class="ai-bundle-art"><img src="${bundle.image}" alt="${bundle.name} AI toolkit" width="1536" height="1536"><span aria-hidden="true">+</span><img src="/assets/ai-compliance-for-small-business-uk-edition.webp" alt="AI Compliance for Small Business UK Edition blueprint cover" width="420" height="590"></div><div><p class="eyebrow">TOOLKIT + BLUEPRINT BUNDLE</p><h3>${bundle.name} toolkit + UK AI compliance blueprint</h3><p>The editable working tools together with the existing <strong>25-page Version 1.1 AI Compliance for Small Business (UK Edition)</strong> PDF blueprint shown below.</p><p>Includes all ${bundle.count} toolkit items, both Excel workbooks and the blueprint PDF. The blueprint is a separate publication and may have a different information date; it is not the separate companion guide referenced in the toolkit.</p><div class="ai-buy"><strong>£${config.bundleUkTotal}</strong><span>UK total including 20% VAT</span></div>${config.bundleUrl?`<a class="button primary" href="${config.bundleUrl}">Buy toolkit + blueprint ↗</a>`:'<button class="button" disabled>Bundle checkout being prepared</button>'}<p class="purchase-note">One bundle purchase includes the toolkit and blueprint. No need to buy either separately. Gumroad adds applicable local tax at checkout.</p></div></article>
<a class="quiet-link" href="#blueprint">Prefer the blueprint on its own? Explore it below ↓</a>
</section>`}
