import {readFileSync} from 'node:fs';
import {layout,esc} from './site.mjs';
const read=name=>JSON.parse(readFileSync(new URL('../data/'+name+'.json',import.meta.url),'utf8'));
export const landingPages=read('landing-pages').pages;
const packContents=read('packs');
const money=p=>new Intl.NumberFormat('en-GB',{style:'currency',currency:p.currency||'GBP',minimumFractionDigits:Number.isInteger(p.price)?0:2,maximumFractionDigits:2}).format(p.price);
const path=p=>'/products/'+p.handle+'/';
export function landingPage(d,products){
  const find=h=>{const p=products.find(x=>x.handle===h);if(!p)throw new Error('Landing page references missing product: '+h);return p;};
  const p=find(d.featured),pack=find(d.pack),members=packContents[pack.handle].map(find);
  const total=members.reduce((n,x)=>n+x.price,0),saving=total-pack.price;
  const buy=(item,label,position)=>`<a class="button primary" href="${esc(item.payhipUrl)}" data-landing-action="checkout" data-product-handle="${item.handle}" data-position="${position}">${label} — ${money(item)} <span aria-hidden="true">↗</span></a>`;
  const sample=(s,i)=>`<button class="lp-sample" data-sample="${s.src}" data-alt="${esc(s.alt)}" data-landing-action="preview" data-position="sample-${i+1}" data-product-handle="${p.handle}"><div class="lp-sample-paper"><img src="${s.src}" alt="${esc(s.alt)}" width="778" height="1100" loading="lazy"></div><span>${esc(s.label)} <b aria-hidden="true">↗</b></span><small>${esc(s.caption)}</small></button>`;
  const commonFaqs=[['How will I receive my files?','Payhip handles the purchase and digital delivery. After checkout, use the download page or the link in your receipt email. This is a PDF purchase, not a printed book.'],['Can I inspect the PDF before buying?','Yes. Open the sample pages above to see the actual contents and page layout. The samples are available without entering an email address.'],['Are future updates included?','This page describes the edition offered now. It does not promise automatic updates or a subscription. Contact support if you need to confirm an edition before buying.'],['Where can I ask a question or read the refund policy?','Contact support@pdfblueprints.store with product or download questions. Read the refund policy linked below before purchasing. Your statutory rights are unaffected.']];
  const body=`<div class="landing" data-landing-page="${d.slug}">
  <div class="wrap lp-breadcrumb"><a href="/">PDFBlueprints</a><span>/</span>${esc(d.navLabel)}</div>
  <section class="wrap lp-hero"><div class="lp-hero-copy"><p class="eyebrow">${esc(d.audience)}</p><h1>${esc(d.headline)}<br><em>${esc(d.emphasis)}</em></h1><p class="lp-intro">${esc(d.intro)}</p><div class="lp-actions">${buy(p,'Buy the PDF','hero')}<a class="quiet-link" href="#preview">See real sample pages ↓</a></div><p class="lp-checkout-note">One-off purchase · PDF delivery through Payhip<br>Any applicable tax is shown before payment.</p><div class="lp-facts"><span><strong>${d.pageCount}</strong> pages</span><span><strong>2</strong> real previews</span><span><strong>No</strong> subscription</span></div></div><div class="lp-hero-art"><div class="lp-art-top"><span>YOUR PRACTICAL STARTING POINT</span><span>01</span></div><img src="${p.image}" alt="${esc(p.title)} cover" width="350" height="495" fetchpriority="high"><div class="lp-art-bottom"><strong>${esc(p.title)}</strong><span>${esc(d.edition)}</span></div></div></section>
  <nav class="lp-jump" aria-label="On this page"><div class="wrap"><a href="#fit">Is it for me?</a><a href="#preview">See inside</a><a href="#options">Guide or pack?</a><a href="#questions">Questions</a></div></nav>
  <section class="wrap lp-section" id="fit"><p class="eyebrow">START WITH YOUR SITUATION</p><h2>A useful next step.<br><em>Wherever you are now.</em></h2><div class="lp-three">${d.situations.map(([h,t],i)=>`<article><span class="lp-number">0${i+1}</span><h3>${esc(h)}</h3><p>${esc(t)}</p></article>`).join('')}</div><p class="lp-scope">${esc(d.scope)}</p></section>
  <section class="lp-tint"><div class="wrap lp-section"><div class="lp-section-heading"><div><p class="eyebrow">FROM READING TO DOING</p><h2>Put the guidance<br><em>to work.</em></h2></div><p>Read the relevant section.<br>Use the tools. Record your next step.</p></div><div class="lp-benefits">${d.benefits.map(([h,t])=>`<article><h3>${esc(h)}</h3><p>${esc(t)}</p></article>`).join('')}</div></div></section>
  <section class="wrap lp-section" id="preview"><div class="lp-section-heading"><div><p class="eyebrow">REAL PAGES. NO GUESSWORK.</p><h2>Look inside<br><em>before you decide.</em></h2></div><p>These are pages from the PDF.<br>Select a sample to read it at full size.</p></div><div class="lp-previews">${d.samples.map(sample).join('')}</div></section>
  <section class="wrap lp-section lp-included"><div><p class="eyebrow">WHAT YOUR PURCHASE INCLUDES</p><h2>One guide.<br><em>A practical reference.</em></h2><p>${esc(d.edition)} · ${d.pageCount} pages</p><a class="quiet-link" href="${path(p)}">Read the full product details ↗</a></div><ul>${d.contents.map(t=>`<li><span aria-hidden="true">✓</span>${esc(t)}</li>`).join('')}</ul></section>
  <section class="lp-offer-band" id="options"><div class="wrap lp-section"><p class="eyebrow">CHOOSE WHAT FITS</p><h2>Start with the guide.<br><em>Or take the next step together.</em></h2><div class="lp-offers"><article><p class="micro">THE FOCUSED START</p><h3>${esc(p.title)}</h3><p>${d.pageCount}-page PDF · ${esc(d.edition)}</p><strong class="lp-price">${money(p)}</strong>${buy(p,'Buy the PDF','offer-guide')}<a class="quiet-link" href="${path(p)}">Guide details ↗</a></article><article class="lp-pack-offer"><p class="micro">TWO COMPLETE GUIDES${saving>0?' · SAVE '+money({price:saving}):''}</p><h3>${esc(pack.title)}</h3><ul>${members.map(m=>`<li><a href="${path(m)}">${esc(m.title)}</a></li>`).join('')}</ul><div class="lp-price-row"><strong class="lp-price">${money(pack)}</strong>${saving>0?`<span>${money({price:total})} separately</span>`:''}</div>${buy(pack,'Buy the pack','offer-pack')}<a class="quiet-link" href="${path(pack)}">Pack contents and previews ↗</a></article></div><p class="lp-checkout-note">One-off purchases. Secure checkout and file delivery through Payhip. Any applicable tax is shown before payment.</p></div></section>
  <section class="wrap lp-section lp-trust"><div><p class="eyebrow">MAKE AN INFORMED CHOICE</p><h2>Know what you’re buying.<br><em>Know its limits.</em></h2></div><div><h3>Inspect the product itself</h3><p>Real samples, a clear contents list and the edition information help you judge whether this guide fits your needs.</p><h3>A starting point for your decisions</h3><p>Use the guide alongside its official-source references. It does not replace advice tailored to your circumstances or guarantee a particular outcome.</p><a class="quiet-link" href="/about/">About PDFBlueprints ↗</a></div></section>
  ${d.alternative?`<aside class="wrap lp-alternative"><h2>${esc(d.alternative.heading)}</h2><p>${esc(d.alternative.copy)}</p><a class="quiet-link" href="${path(find(d.alternative.handle))}">Explore the separate US guide ↗</a></aside>`:''}
  <section class="wrap lp-section lp-faq" id="questions"><p class="eyebrow">BEFORE YOU BUY</p><h2>A few useful answers.</h2>${[...d.faqs,...commonFaqs].map(([q,a])=>`<details><summary>${esc(q)}</summary><p>${esc(a)}</p></details>`).join('')}<p><a href="/policies/refund-policy/">Read the refund policy</a> · <a href="mailto:support@pdfblueprints.store">Ask a question</a></p></section>
  <section class="wrap lp-final"><div><p class="eyebrow">YOUR NEXT STEP</p><h2>${esc(d.emphasis)}</h2><p>${esc(p.title)} · ${money(p)} · PDF download</p></div><div>${buy(p,'Buy the PDF','final')}<a class="quiet-link" href="#preview">Take another look inside ↑</a></div></section></div>`;
  return layout(d.title,body,d.intro).replace('</head>','<link rel="stylesheet" href="/landing.css?v=20261008"><script src="/landing.js?v=20261008" defer></script></head>');
}
